# The jump host should be in the same network as the cluster.
# The jump_host_ip should be reachable from the client that runs the cluster install.
jump_host_ip: ''

# Your private key local path to connect to all hosts
key_file_path: ''

# The hosts' username, e.g. centos
machine_username: ''

# Local path to a valid Cloudify license
cloudify_license_path: ''

# Manager RPM to install on the cluster instances
manager_rpm_download_link: 'http://cloudify-release-eu.s3.amazonaws.com/cloudify/5.1.0/.dev1-release/cloudify-manager-install-5.1.0-.dev1.el7.x86_64.rpm'

# If specified, all the VMs certificates will need to be specified as well
ca_cert_path: ''

# If using a load-balancer, please provide its IP
load_balancer_ip: ''

# In case you are using a 3 nodes cluster, just fill in the `manager` items
# Otherwise, fill in all items
existing_vms:
    manager-1:
      private_ip: ''
      public_ip: ''
      cert_path: ''
      key_path: ''

    manager-2:
      private_ip: ''
      public_ip: ''
      cert_path: ''
      key_path: ''

    manager-3:
      private_ip: ''
      public_ip: ''
      cert_path: ''
      key_path: ''

    rabbitmq-1:
      private_ip: ''
      public_ip: ''
      cert_path: ''
      key_path: ''

    rabbitmq-2:
      private_ip: ''
      public_ip: ''
      cert_path: ''
      key_path: ''

    rabbitmq-3:
      private_ip: ''
      public_ip: ''
      cert_path: ''
      key_path: ''

external_db_configuration:
  host: '' # The external DB host name (or IP address)
  ca_path: '' # The external DB CA certificate

  # If your database is an Azure DBaaS instance, you must set 'server_username'
  # so it includes the database name as a suffix. For example, if your database
  # name is "mycfydb" and your username is "test", then "server_username"
  # should be "mycfydb@test".
  server_db_name: ''  # master db name
  server_username: ''  # master username to login external database
  server_password: ''  # password of master username to login external database

  # The following apply if your database is an Azure DBaaS instance:
  #
  #   * "cloudify_username" must include the database name as a suffix. For example,
  #     if your desired database username is "cloudify" and your database name is
  #     "test", then "cloudify_username" should be "cloudify@test".
  #
  #   * "cloudify_username" must be different from "server_username".
  cloudify_username: cloudify
  cloudify_password: ''

# If the credentials are not specifid, random ones will be used and written to a dedicated file
credentials: # The values specified here will be deleted at the end of the installation
  rabbitmq_credentials:
    username: ''
    password: ''
  manager_monitoring_credentials:
    username: ''
    password: ''
  rabbitmq_monitoring_credentials:
    username: ''
    password: ''
