manager:
  private_ip: <current postgresql private-ip>
  public_ip: <current postgresql private-ip>

postgresql_server:
  cert_path:
  key_path:
  ca_path:

  ssl_client_verification: true
  ssl_only_connections: true

  postgres_password: 'somesecretvalue123!'
  cluster:
    nodes:
      <first postgresql instance-name>:
        ip:
      <second postgresql instance-name>:
        ip:
      <third postgresql instance-name>:
        ip:

    etcd:
      cluster_token: 'somesecretvalue123!'
      root_password: 'somesecretvalue123!'
      patroni_password: 'somesecretvalue123!'
    patroni:
      rest_password: 'somesecretvalue123!'
    postgres:
      replicator_password: 'somesecretvalue123!'

prometheus:
  credentials:
    username: 'monitoringusername'
    password: 'longyeteasytorememberstringasapassword'

  cert_path:
  key_path:
  ca_path:
    
validations:
  minimum_required_total_physical_memory_in_mb: 1024


services_to_install:
  - database_service
  - monitoring_service
