manager:
  private_ip: {{ node.private_ip }}
  public_ip: {{ node.public_ip }}

rabbitmq:
  username: cloudify
  password: c10udify

  cluster_members: {{ rabbitmq_cluster }}

  cert_path: {{ node.cert_path }}
  key_path: {{ node.key_path }}
  ca_path: {{ ca_path }}

  nodename: {{ node.name }}

  {% if join_cluster %}
  join_cluster: {{ join_cluster }}
  {% endif %}

  erlang_cookie: 'securesharedtoken'

prometheus:
  credentials:
    username: 'monitoringusername'
    password: 'longyeteasytorememberstringasapassword'

  cert_path: {{ node.cert_path }}
  key_path: {{ node.key_path }}
  ca_path: {{ ca_path }}

validations:
  minimum_required_total_physical_memory_in_mb: 1024

services_to_install:
  - queue_service
  - monitoring_service
