apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python
    image: circleci/python:3.6
    resources:
      requests:
        cpu: 0.6
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: python-old
    image: circleci/python:2.7
    command:
      - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: rpmbuild
    image: rpmbuild/centos7
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 0.6
    securityContext:
      runAsUser: 0
      privileged: true
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot
