def secrets = [
  [path: 'secret/jenkins/github', engineVersion: 2, secretValues: [
    [envVar: 'PRIVATE_REPO_GITHUB_TOKEN', vaultKey: 'private_token']]],
]

def configuration = [vaultUrl: "${env.VAULT_URL}",  vaultCredentialId: 'vault-app-role', engineVersion: 2]

def getClusterManagerVersion(String branchName='master'){
  sh returnStdout:true, script: """
    eval "\$(curl 'https://raw.githubusercontent.com/cloudify-cosmo/cloudify-cluster-manager/${branchName}/packaging/version_info')"
    echo "\$CLOUDIFY_CLUSTER_MANAGER_VERSION"
  """
}

def getClusterManagerPreRelease(String branchName='master'){
  sh returnStdout:true, script: """
    eval "\$(curl 'https://raw.githubusercontent.com/cloudify-cosmo/cloudify-cluster-manager/${branchName}/packaging/version_info')"
    echo "\$CLOUDIFY_CLUSTER_MANAGER_PACKAGE_RELEASE"
  """
}

@Library('pipeline-shared-library') _

pipeline {
  agent {
    kubernetes {
      label 'cluster-manager'
      defaultContainer 'jnlp'
      yamlFile 'jenkins/build-pod.yaml'
    }
  }

  options {
    checkoutToSubdirectory('cloudify-cluster-manager')
    buildDiscarder(logRotator(numToKeepStr:'30'))
    timeout(time: 60, unit: 'MINUTES')
    timestamps()
  }

  environment {
    BRANCH = "${env.BRANCH_NAME}"
    PROJECT = "cloudify-cluster-manager"
    VERSION=getClusterManagerVersion("${env.BRANCH_NAME}").trim()
    PRERELEASE = getClusterManagerPreRelease("${env.BRANCH_NAME}").trim()
    S3_BUILD_PATH = "${env.PROJECT}/${env.VERSION}/${env.PRERELEASE}-build/${env.BRANCH}"
  }

  stages{
    stage('Prepare') {
      steps {
        repoCheckout('https://github.com/cloudify-cosmo/cloudify-cluster-manager.git',"${env.PROJECT}","${env.BRANCH}")
        container('python'){
          sh '''
            apt-get update
            apt-get install libldap-dev libsasl2-dev
            virtualenv ~/venv
          '''
        }
      }
    }
    stage('flake8'){
      steps{
        sh script: "mkdir -p ${env.WORKSPACE}/flake8 && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/flake8", label: "copying repo to seperate workspace"

        container('python'){
          dir("${env.WORKSPACE}/flake8") {
            echo 'install flake 8'
            sh 'pip install flake8 --user'
            echo 'run flake8'
            sh 'python -m flake8 cfy_cluster_manager tests'
          }
        }
      }
    }
    stage('py3 compat'){
      steps {
        sh script: "mkdir -p ${env.WORKSPACE}/py3_compat && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/py3_compat", label: "copying repo to seperate workspace"

        container('python-old'){
          dir("${env.WORKSPACE}/py3_compat") {
            echo 'install futurize and find python3-incompatible code'
            sh '''#!/bin/bash
              pip install future --user
              PATH=$PATH:~/.local/bin

              FUTURIZE="futurize ."
              while read line; do
              [[ "$line" =~ ^#.* ]] && continue
              FUTURIZE="${FUTURIZE} ${line}"
              done<jenkins/py3fixers
              $FUTURIZE>futurize_diffs
            '''

            echo 'check that there is no python3-incompatible code'
            sh '''#!/bin/bash
                if [[ -s futurize_diffs ]]; then
                echo "Python-3-incompatible code found"
                cat futurize_diffs
                exit 1
                fi
            '''
          }
        }
      }
    }
    stage('Run Tests'){
      steps{
        sh script: "mkdir -p ${env.WORKSPACE}/test-cfy-cluster-manager && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/test-cfy-cluster-manager", label: "copying repo to seperate workspace"
        container('python'){
          dir("${env.WORKSPACE}/test-cfy-cluster-manager") {
            sh script: '''
              ~/venv/bin/pip install -Ur dev-requirements.txt
              ~/venv/bin/pip install -Ur test-requirements.txt
              ~/venv/bin/pip install -e .
            ''', label: "installing requirements for pytest"
            echo 'Running pytest'
            sh '~/venv/bin/pytest tests'
          }
        }
      }
    }
    stage('Build RPM'){
      steps{
        container('rpmbuild'){
          sh """
            cd && mkdir rpmbuild && cd rpmbuild
            git clone --single-branch --branch ${env.BRANCH} https://github.com/cloudify-cosmo/cloudify-cluster-manager.git SOURCES && cd SOURCES
          """

          echo 'Download sources for RPM spec file & Build RPM'
          sh "yum install rpmdevtools -y"

          echo 'Build Cloudify Cluster Manager RPM'
          buildRpm('~/rpmbuild/SOURCES', 'cloudify-cluster-manager.spec', "${env.VERSION}", "${env.PRERELEASE}")

          echo 'Copy RPM to rpm folder'
          sh("mkdir -p ${env.WORKSPACE}/rpm && cp -rf /root/rpmbuild/RPMS/x86_64/. ${env.WORKSPACE}/rpm")
        }
      }
      post {
        success {
          echo 'Upload artifacts to S3'
          uploadToReleaseS3("${env.WORKSPACE}/rpm/","${env.S3_BUILD_PATH}")
        }
      }
    }
  }
}
