# Your private key local path to connect to all hosts
key_file_path: ''

# The hosts' username, e.g. centos
machine_username: ''

# Local path to a valid Cloudify license
cloudify_license_path: ''

# Manager RPM to install on the cluster instances
manager_rpm_download_link: 'http://cloudify-release-eu.s3.amazonaws.com/cloudify/5.1.0/.dev1-release/cloudify-manager-install-5.1.0-.dev1.el7.x86_64.rpm'

# If specified, all the VMs certificates will need to be specified as well
ca_cert_path: ''

# If using a load-balancer, please provide its IP.
# This IP will be written the the config.yaml files.
load_balancer_ip: ''


existing_vms:
    node-1:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # As specified in the certificate (if specified). Optional
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied

    node-2:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # As specified in the certificate (if specified). Optional
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied

    node-3:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # As specified in the certificate (if specified). Optional
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied


# If the credentials are not specified, random ones will be used and written to {{ credentials_file_path }}
credentials:
  manager:
    admin_username: 'admin'
    admin_password: ''

  postgresql:
    postgres_password: ''
    cluster:
      etcd:
        cluster_token: ''
        root_password: ''
        patroni_password: ''
      patroni:
        rest_password: ''
      postgres:
        replicator_password: ''

    db_monitoring:
      username: ''
      password: ''

  rabbitmq:
    username: ''
    password: ''
    erlang_cookie: ''

  prometheus:
    username: ''
    password: ''
