# Your private key local path to connect to all hosts
key_file_path: ''

# The hosts' username, e.g. centos
machine_username: ''

# Local path to a valid Cloudify license
cloudify_license_path: ''

# Manager RPM to install on the cluster instances
manager_rpm_download_link: 'http://cloudify-release-eu.s3.amazonaws.com/cloudify/5.1.0/.dev1-release/cloudify-manager-install-5.1.0-.dev1.el7.x86_64.rpm'

# If specified, all the VMs certificates will need to be specified as well
ca_cert_path: ''

# If using a load-balancer, please provide its IP.
# This IP will be written the the config.yaml files.
load_balancer_ip: ''


existing_vms:
    manager-1:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # As specified in the certificate (if specified). Optional
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied

    manager-2:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # As specified in the certificate (if specified). Optional
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied

    manager-3:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # As specified in the certificate (if specified). Optional
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied

    rabbitmq-1:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # As specified in the certificate (if specified). Optional
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied

    rabbitmq-2:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # As specified in the certificate (if specified). Optional
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied

    rabbitmq-3:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # As specified in the certificate (if specified). Optional
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied


external_db_configuration:
  host: '' # The external DB host name (or IP address)
  ca_path: '' # The external DB CA certificate

  # If your database is an Azure DBaaS instance, you must set 'server_username'
  # so it includes the database name as a suffix. For example, if your database
  # name is "mycfydb" and your username is "test", then "server_username"
  # should be "mycfydb@test".
  server_db_name: ''  # master db name
  server_username: ''  # master username to login external database
  server_password: ''  # password of master username to login external database

  # The following apply if your database is an Azure DBaaS instance:
  #
  #   * "cloudify_username" must include the database name as a suffix. For example,
  #     if your desired database username is "cloudify" and your database name is
  #     "test", then "cloudify_username" should be "cloudify@test".
  #
  #   * "cloudify_username" must be different from "server_username".
  cloudify_db_name: cloudify_db
  cloudify_username: cloudify
  cloudify_password: ''


# If the credentials are not specified, random ones will be used and written to {{ credentials_file_path }}
credentials:
  manager:
    admin_username: 'admin'
    admin_password: ''

  rabbitmq:
    username: ''
    password: ''
    erlang_cookie: ''

  prometheus:
    username: ''
    password: ''
